services:
  postgres:
    image: postgres
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - /Users/amentag/Desktop/T_DB:/var/lib/postgresql/data
    restart: unless-stopped