version: '3.8'

networks:
  app-network:

services:
  backend:
    container_name: web
    depends_on:
      - postgres
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - app-network

  postgres:
    container_name: postgres
    image: postgres:16.3
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - /Users/amentag/Desktop/T_DB:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network