version: "3.8"

networks:
  app-network:

services:
  backend:
    container_name: backend
    depends_on:
      - postgres
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - /goinfre/amentag/Trenscendence/backend:/app
    env_file:
      - .env
    networks:
      - app-network

  frontend:
    container_name: frontend
    depends_on:
      - backend
    build: ./frontend
    ports:
      - "5252:5252"
    volumes:
      - /goinfre/amentag/Trenscendence/frontend:/app
    networks:
      - app-network

  postgres:
    container_name: postgres
    image: postgres:16.3
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - /goinfre/amentag/db:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

# volumes:
#   backend:
#     driver_opts:
#       device: /goinfre/amentag/Trenscendence/backend
#       type: none
#       o: bind
#   frontend:
#     driver_opts:
#       device: /goinfre/amentag/Trenscendence/frontend
#       type: none
#       o: bind
  # db:
  #   driver_opts:
  #     device: /goinfre/amentag/db
  #     type: none
  #     o: bind