version: "3.8"

networks:
  app-network:

services:
  backend:
    container_name: backend
    depends_on:
      - postgres
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - app-network

  frontend:
    container_name: frontend
    depends_on:
      - backend
    build: ./frontend
    ports:
      - "7000:7000"
    networks:
      - app-network

  postgres:
    container_name: postgres
    image: postgres:16.3
    env_file:
      - .env
    ports:
      - "5432:5432"
    # volumes:
    #   - /Users/yel-hajj/goinfre/T_DB:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network
